### ISSUE TITLE
Self-Deploying

### ISSUE THREAD

**Issue by ehousse** [philjorgensen/Intune#2]
Is it possible to configure the autopilot detection to work with Self-Deploying mode?

**Comment by philjorgensen** [comment]
Are you referring to the Get-LnvUpdates solution that uses Thin Installer? If so, Self-Deploy mode _should_ work without having to change the detection.

**Comment by ehousse** [comment]
Sorry about that putting the issue under the wrong area.  I've recently upgraded to 23H2, but ran autopilot a few times, it kept showing non-applicable.  I assume that would be an issue with the detection script.

**Comment by philjorgensen** [comment]
I'm experiencing the same behavior. What doesn't make sense is the detection script still returns defaultuser0 as the current logged on user during Self-Deploy so I have no idea why the app is skipped.

Edit:

Rather than using the script detection, try adding this Registry requirement rule detection. This worked for me in Self-Deploy:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
DefaultUserName
Select String comparison
Select Equals
defaultuser0

**Comment by ehousse** [comment]
Trying it now, thanks for the quick responses.  I was on W11 23H2, maybe something changed? "Associated with a 32-bit app on 64-bit clients: Yes" still the same?

**Comment by philjorgensen** [comment]
> Trying it now, thanks for the quick responses. I was on W11 23H2, maybe something changed? "Associated with a 32-bit app on 64-bit clients: Yes" still the same?

Wouldn't be surprised if something changed in 23H2. I haven't tested yet.

"Associated with a 32-bit app on 64-bit clients": Set this to No
